Add configure option to disable LTO/gold
Port of https://lists.freedesktop.org/archives/systemd-devel/2015-February/028544.html

We need this because ld.gold from GCC 8 failed to link-time optimize systemd-230:
/usr/bin/ld.gold: ./.libs/libjournal-core.a(bus-bloom.o): previous definition here
/usr/bin/ld.gold: error: ./.libs/libjournal-core.a(bus-error.o): multiple definition of 'bus_standard_errors'